# Generated by Django 4.0.3 on 2022-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email_signup',
            field=models.CharField(default='testing@gmail.com', max_length=150),
        ),
    ]
