# Generated by Django 4.0.3 on 2022-03-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_signup_email_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
