# Generated by Django 4.0.3 on 2022-03-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email_signup',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password_signup',
            new_name='password',
        ),
    ]
