# Generated by Django 4.0.3 on 2022-03-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_rename_signup_users_rename_email_signup_users_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
