# Generated by Django 4.0.2 on 2022-03-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='State',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ZipCode',
            field=models.CharField(max_length=9),
        ),
    ]
