# Generated by Django 4.0.2 on 2022-03-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_userinfo_address2_alter_userinfo_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Address2',
            new_name='Address2field',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Address',
            new_name='Addressfield',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='City',
            new_name='Cityfield',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Name',
            new_name='Namefield',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='State',
            new_name='Statefield',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='ZipCode',
            new_name='ZipCodefield',
        ),
    ]
