# Generated by Django 4.0.2 on 2022-04-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_alter_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='invaliddata', max_length=100, primary_key=True, serialize=False),
        ),
    ]
