# Generated by Django 4.0.2 on 2022-04-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_remove_userinfo_id_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Namefield',
            field=models.CharField(max_length=50),
        ),
    ]
