# Generated by Django 4.0.2 on 2022-04-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_rename_userinfo_userinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoz',
            fields=[
                ('username', models.CharField(default='invaliddata', max_length=100, primary_key=True, serialize=False)),
                ('Namefield', models.CharField(max_length=50)),
                ('Addressfield', models.CharField(max_length=100, unique=True)),
                ('Address2field', models.CharField(blank=True, max_length=100)),
                ('Cityfield', models.CharField(max_length=100)),
                ('Statefield', models.CharField(max_length=2)),
                ('ZipCodefield', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfos',
        ),
    ]
