# Generated by Django 4.0.3 on 2022-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.IntegerField(max_length=10000)),
                ('delivery', models.DateField()),
                ('sugPrice', models.FloatField(max_length=10000)),
                ('totalPrice', models.FloatField(max_length=10000)),
            ],
        ),
    ]
