# Generated by Django 4.0.3 on 2022-04-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fueldata', '0003_fueldata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueldata',
            name='username',
            field=models.CharField(default='invaliddata', max_length=100),
        ),
    ]
